In [2]:
import numpy as np

In [8]:
data = np.array([1,2])
print(data)

[1 2]


In [9]:
ones = np.ones(2)
ones

array([1., 1.])

In [6]:
zeros = np.zeros(3)
zeros

array([0., 0., 0.])

In [7]:
random = np.random.rand(3)
random

array([0.0713709 , 0.42497585, 0.82026263])

In [ ]:
print(data + ones)
print(data * data)
print(data - ones)
print(data / data)
print(data * 1.6) #broadcasting example 

[2. 3.]
[1 4]
[0. 1.]
[1. 1.]
[1.6 3.2]


In [ ]:
#indexing
data_3 = np.array([1,2,3])
print(data_3[0])  # First element
print(data_3[1])  # Second element
print(data_3[2])  # Third element
print(data_3[-1]) # Last element
print(data_3[-2]) # Second last element
print(data_3[-3]) # Third last element
print(data_3[:2]) # Slicing: first two elements or print(data_3[0:2])
print(data_3[1:3]) # Slicing: last two elements or print(data_3[1:])

1
2
3
3
2
1
[1 2]
[2 3]


In [20]:
print(data_3.max())  # Maximum value
print(data_3.min())  # Minimum value
print(data_3.sum())  # Sum of all elements
print(data_3.mean()) # Mean of all elements
print(data_3.std())  # Standard deviation

3
1
6
2.0
0.816496580927726


In [21]:
print(np.array([[1,2,3],[4,5,6]]))  # 2D array

[[1 2 3]
 [4 5 6]]


In [30]:
print(np.ones((2,3)))  # 2D array of ones
print(np.zeros((3,2)))  # 2D array of zeros

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [37]:
print(np.ones((1,3)) * np.zeros((2,3)))  # Element-wise multiplication of 2D arrays

[[0. 0. 0.]
 [0. 0. 0.]]
