In [2]:
import numpy as np

In [8]:
data = np.array([1,2])
print(data)

[1 2]


In [9]:
ones = np.ones(2)
ones

array([1., 1.])

In [6]:
zeros = np.zeros(3)
zeros

array([0., 0., 0.])

In [7]:
random = np.random.rand(3)
random

array([0.0713709 , 0.42497585, 0.82026263])

In [12]:
print(data + ones)
print(data * data)
print(data - ones)
print(data / data)
print(data * 1.6) #broadcasting example 

[2. 3.]
[1 4]
[0. 1.]
[1. 1.]
[1.6 3.2]


In [19]:
#indexing
data_3 = np.array([1,2,3])
print(data_3[0])  # First element
print(data_3[1])  # Second element
print(data_3[2])  # Third element
print(data_3[-1]) # Last element
print(data_3[-2]) # Second last element
print(data_3[-3]) # Third last element
print(data_3[:2]) # Slicing: first two elements or print(data_3[0:2])
print(data_3[1:3]) # Slicing: last two elements or print(data_3[1:])

1
2
3
3
2
1
[1 2]
[2 3]


In [20]:
print(data_3.max())  # Maximum value
print(data_3.min())  # Minimum value
print(data_3.sum())  # Sum of all elements
print(data_3.mean()) # Mean of all elements
print(data_3.std())  # Standard deviation

3
1
6
2.0
0.816496580927726


In [21]:
print(np.array([[1,2,3],[4,5,6]]))  # 2D array

[[1 2 3]
 [4 5 6]]


In [30]:
print(np.ones((2,3)))  # 2D array of ones
print(np.zeros((3,2)))  # 2D array of zeros

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [53]:
# Matrix multiplication (correct way)
A = np.ones((2,3))  # 2x3 matrix
B = np.zeros((3,2))  # 3x2 matrix

print("Matrix A (2x3):")
print(A)
print("\nMatrix B (3x2):")
print(B)

# Matrix multiplication using @ operator
print("\nMatrix multiplication A @ B:")
print(A @ B)

# Alternative ways to do matrix multiplication:
print("\nUsing np.matmul():")
print(np.matmul(A, B))

print("\nUsing np.dot():")
print(np.dot(A, B))

Matrix A (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]

Matrix B (3x2):
[[0. 0.]
 [0. 0.]
 [0. 0.]]

Matrix multiplication A @ B:
[[0. 0.]
 [0. 0.]]

Using np.matmul():
[[0. 0.]
 [0. 0.]]

Using np.dot():
[[0. 0.]
 [0. 0.]]


In [54]:
# Demonstrating the difference between * and @ operators
C = np.array([[1, 2], [3, 4]])
D = np.array([[5, 6], [7, 8]])

print("Matrix C:")
print(C)
print("\nMatrix D:")
print(D)

print("\nElement-wise multiplication (C * D):")
print(C * D)

print("\nMatrix multiplication (C @ D):")
print(C @ D)

Matrix C:
[[1 2]
 [3 4]]

Matrix D:
[[5 6]
 [7 8]]

Element-wise multiplication (C * D):
[[ 5 12]
 [21 32]]

Matrix multiplication (C @ D):
[[19 22]
 [43 50]]


# Torch

In [55]:
import torch

In [56]:
# 1. Φτιάχνουμε έναν πίνακα με τυχαία νούμερα
# Διαστάσεις: 2 (Batch Size) x 3 (Μήκος πρότασης) x 4 (Embedding Size)
# Σκέψου το σαν: 2 προτάσεις, η καθεμία έχει 3 λέξεις, κάθε λέξη περιγράφεται από 4 αριθμούς.
x = torch.rand(2, 3, 4)
print(x)

tensor([[[0.9521, 0.6181, 0.8752, 0.0954],
         [0.6981, 0.0842, 0.6364, 0.1912],
         [0.0823, 0.8363, 0.4081, 0.9868]],

        [[0.6572, 0.3113, 0.6075, 0.0422],
         [0.1168, 0.9946, 0.5162, 0.3861],
         [0.9865, 0.5437, 0.3789, 0.2740]]])


### Shape

In [58]:
print(f"Shape: {x.shape}")
#πόσες προτάσεις (Batch Size) έχει μέσα αυτός ο Tensor
print(x.shape[0])

Shape: torch.Size([2, 3, 4])
2


### Squeeze/Unsqueeze

In [60]:
sentence = torch.rand(3, 4)  # Μία πρόταση με 3 λέξεις, κάθε λέξη με 4 διαστάσεις
print(sentence)
print(f"Shape of sentence tensor: {sentence.shape}")

tensor([[0.3535, 0.3183, 0.6344, 0.0784],
        [0.1190, 0.5808, 0.0083, 0.5571],
        [0.5009, 0.1855, 0.2143, 0.0483]])
Shape of sentence tensor: torch.Size([3, 4])


In [62]:
batch_sentence = sentence.unsqueeze(0)  # Προσθέτουμε διάσταση batch
print(batch_sentence)
print(f"Shape of batch sentence tensor: {batch_sentence.shape}")

tensor([[[0.3535, 0.3183, 0.6344, 0.0784],
         [0.1190, 0.5808, 0.0083, 0.5571],
         [0.5009, 0.1855, 0.2143, 0.0483]]])
Shape of batch sentence tensor: torch.Size([1, 3, 4])


In [63]:
unbatch_sentence = batch_sentence.squeeze(0)  # Αφαιρούμε τη διάσταση batch
print(unbatch_sentence)
print(f"Shape of unbatched sentence tensor: {unbatch_sentence.shape}")

tensor([[0.3535, 0.3183, 0.6344, 0.0784],
        [0.1190, 0.5808, 0.0083, 0.5571],
        [0.5009, 0.1855, 0.2143, 0.0483]])
Shape of unbatched sentence tensor: torch.Size([3, 4])


### View/Reshape


In [72]:
flat_data = torch.rand(8)  # Ένας απλός 1D Tensor με 8 στοιχεία
print(flat_data)

tensor([0.5944, 0.0800, 0.5065, 0.1768, 0.1384, 0.5202, 0.9190, 0.7697])


In [73]:
#change of shape
reshaped_data = flat_data.view(4, 2)  # Αλλάζουμε το σχήμα σε 2x4
print(reshaped_data)

tensor([[0.5944, 0.0800],
        [0.5065, 0.1768],
        [0.1384, 0.5202],
        [0.9190, 0.7697]])


### GPU vs CPU Tensors

In [71]:
x = torch.rand(2, 3, 4)

print(f"Original tensor device: {x.device}")
print(f"CUDA available: {torch.cuda.is_available()}")

#move to gpu if available
if torch.cuda.is_available():
    x_gpu = x.to('cuda')
    print(f"GPU tensor device: {x_gpu.device}")
    print("Tensor moved to GPU")
else:
    print("CUDA is not available. Tensor remains on CPU")
    print(f"CPU tensor device: {x.device}")

Original tensor device: cpu
CUDA available: False
CUDA is not available. Tensor remains on CPU
CPU tensor device: cpu


Email excercise / urgent vs non-urgent


In [74]:
import torch.nn.functional as F

In [75]:
# Σκληροπυρηνικά δεδομένα για το παράδειγμα (Logits)
# Email A: Πολύ μεγάλο σκορ στο "Ασήμαντο" (4.5 vs -2.0)
# Email B: Μπερδεμένο, λίγο προς το "Επείγον" (0.1 vs 0.2)
# Email C: Πολύ μεγάλο σκορ στο "Επείγον" (-3.0 vs 5.0)
logits = torch.tensor([
    [ 4.5, -2.0],  # Email A (ID: 101)
    [ 0.1,  0.2],  # Email B (ID: 102)
    [-3.0,  5.0]   # Email C (ID: 103)
])

print(f"Shape: {logits.shape}")

Shape: torch.Size([3, 2])


### apply softmax fro logit probabilites

In [76]:
probs = F.softmax(logits, dim=1)
print(probs)

tensor([[9.9850e-01, 1.5012e-03],
        [4.7502e-01, 5.2498e-01],
        [3.3535e-04, 9.9966e-01]])


In [77]:
urgent_scores = probs[:, 1]

print(f"Urgent Scores: {urgent_scores}")
print(f"Shape: {urgent_scores.shape}")

Urgent Scores: tensor([0.0015, 0.5250, 0.9997])
Shape: torch.Size([3])


### threshold filtering/masking


In [78]:
threshold = 0.9

# create true false mask
is_urgent = urgent_scores > threshold

print(f"Is Urgent Mask: {is_urgent}")

Is Urgent Mask: tensor([False, False,  True])


### retrieval

In [81]:
# Βρες τις θέσεις που είναι True
indices = is_urgent.nonzero()

print(f"Indices: {indices}")
# Output: tensor([[2]]) -> Το email στη θέση 2 (το 3ο email δηλαδή)


# Μετατροπή σε απλή λίστα Python
urgent_email_indices = indices.squeeze().tolist() 
print(urgent_email_indices)

# Χειρισμός αν είναι ένας αριθμός ή λίστα
if isinstance(urgent_email_indices, int):
    urgent_email_indices = [urgent_email_indices]

print(f"Send these indices to DB: {urgent_email_indices}")

Indices: tensor([[2]])
2
Send these indices to DB: [2]


### Padding/attention mask

In [82]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

emails = [
    "Hello",                   # Μικρό email
    "Please help me right now" # Μεγάλο email
]

# Ο Tokenizer το κάνει αυτόματα για σένα με το padding=True
inputs = tokenizer(emails, padding=True, return_tensors="pt")

print("Input IDs (Τα δεδομένα):")
print(inputs['input_ids'])

print("\nAttention Mask (Ο οδηγός):")
print(inputs['attention_mask'])


c:\Users\Theo\source\repos\AUEB\LangChain\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\Theo\source\repos\AUEB\LangChain\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Theo\.cache\huggingface\hub\models--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In orde

Input IDs (Τα δεδομένα):
tensor([[ 101, 7592,  102,    0,    0,    0,    0],
        [ 101, 3531, 2393, 2033, 2157, 2085,  102]])

Attention Mask (Ο οδηγός):
tensor([[1, 1, 1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1]])
